### ISSUE TITLE
sleep Problem

### ISSUE THREAD

**Issue by MohammadtaghiFarkhondekar** [chris1111/VoodooHDA-2.9.0-Clover-V12#5]
HI 
I use your app - EFI - clover mode best work on gl553vd but when i do volume to down sound play with the noise !!
but but the bit problem is sleep problem because when laptop go to sleep and after wake up sound doesn't work !! please fix this . 
thank you

**Comment by chris1111** [comment]
Did you read here https://www.insanelymac.com/forum/topic/267905-voodoohda-common-problems/
