### ISSUE TITLE
Big problem with microphone noise

### ISSUE THREAD

**Issue by eamigo86** [chris1111/VoodooHDA-2.9.0-Clover-V12#6]
Hi, I have been able to obtain a better volume by following its guide, but the microphone is kept with a lot of noise and it is impossible for me to use it. What I can do?

Note:
- The output audio is perfect (both: on board and headphones)
- OS Mojave 10.14.2
- Hardware: Dell XPS 9570, i7 8750H, 16GB RAM, 4K touchscreen version

**Comment by chris1111** [comment]
Try to change some value in infos.plist
<key>MixerValues</key>
			<dict>
				<key>PCM</key>
				<integer>90</integer>
				<key>Rec</key>
				<integer>90</integer>
				<key>iGain</key>
				<integer>0</integer>
				<key>iMix</key>
				<integer>70</integer>
			</dict>

Have a look here
https://olarila.com/forum/viewtopic.php?t=454

**Comment by eamigo86** [comment]
Hi @chris1111,  thanks for quick answer. With this config I gain volume output but gain in the microphone's passive noise too.

**Comment by chris1111** [comment]
> Hi @chris1111, thanks for quick answer. With this config I gain volume output but gain in the microphone's passive noise too.

Try to see here oldnapalm recommandation
https://olarila.com/forum/viewtopic.php?t=454

**Comment by eamigo86** [comment]
Hi @chris1111, thanks for the advice and reference. Now the microphone and audio work great. Thanks!!!!

**Comment by chris1111** [comment]
> Hi @chris1111, thanks for the advice and reference. Now the microphone and audio work great. Thanks!!!!

Please share What is your setup?

**Comment by eamigo86** [comment]
I'm using the latest VoodooHDA version (2.9.1, on Mojave 10.14.2). And this is the modification made to Info.plist
```xml
<key>MixerValues</key>
    <dict>
	<key>PCM</key>
	<integer>90</integer>
	<key>Rec</key>
	<integer>90</integer>
	<key>iGain</key>
	<integer>0</integer>
	<key>iMix</key>
	<integer>30</integer>
    </dict>
```

I'm also use the VoodooHDA-2.9.0-Clover-V12-12 for customize the micro's "Recording Level" about 40%, as seen in the image:
![image](https://user-images.githubusercontent.com/11740026/50405607-c9596780-07b7-11e9-9198-122a027aa8e9.png)

Do not change the configuration of the Headphone nor onboard output.

**Comment by chris1111** [comment]
Thanks
there is no difference of VoodooHDA 2.9.0 to 2.9.1

**Comment by chris1111** [comment]
I iiil update 2.9.0 with this
<key>MixerValues</key>
    <dict>
	<key>PCM</key>
	<integer>90</integer>
	<key>Rec</key>
	<integer>90</integer>
	<key>iGain</key>
	<integer>0</integer>
	<key>iMix</key>
	<integer>30</integer>
    </dict>

**Comment by deskbhaktjain** [comment]
please help me I'm using Mac OS X Catalina on my i7 laptop vodoohda working fine except **microphone**
where to copy ? 
what to copy 
where should I copy these lines written above please help me guys im using voddoohda 2.9.2 v15 clover if you share screenshot where to copy it would be really helpful plz help
